---
- 
  name: This playbook is for jeniins and ansbile porject
  hosts: all
  tasks:
    -
       name: installing apache webeserver
       apt:
         name: apache2
         state: present
    -
        name: configuring web page
        copy:
          content: "<h1> this file has been breated from a ci build of jenkins</h1>"
          dest: /var/www/html/index.html
  
