---
- 
  name: This playbook is for jeniins and ansbile porject
  hosts: all
  tasks:
    -
       name: installing apache webeserver
       apt:
         name: apache2
         state: present
    -
       name: configuring web page
       copy:
         content: "this file has been breated from a ci build of jenkins"
         dest: /var/www/html/index.html
        
    -
       name: starting webserver services
       service:
         name: apache2
         state: started
  
